[package]
name = "Scaling_Project"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
# tokio = {version = "1", features = ["full"]}
# clap = {version = "4", features = ["cargo"]}

[dev-dependencies]
anyhow = "1"
